### ISSUE TITLE
报错 iOS9的sdk方法 development target 是8.2

### ISSUE THREAD

**Issue by dymost** [chatwyn/WBZhiHuDailyPaper#1]
在 HomePageController中 setUpDataSource 中[self registerForPreviewingWithDelegate:cell sourceView:cell.contentView]; 
报为识别消息的错误

**Comment by dymost** [comment]
在 HomePageController中 setUpDataSource方法中
self.newsArrayDataSource = [[ArrayDataSource alloc]initWithItems:self.stories
报
<Error>: CGContextRestoreGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

**Comment by chatwyn** [comment]
thanks,我再看看
